################################# Default configuration ###################
baseURL = "https://www.mvkeilberg.de"
title = "Musikverein Keilberg e.V."
theme = "MVKeilberg"
# disable language
defaultContentLanguage = "de"
timeout = "10m"
disableKinds = ['rss']


################### German Navigation ########################
[[menu.main]]
name = "Aktuelles"
url = "/aktuelles"
weight = 1

[[menu.main]]
name = "Veranstaltungen"
url = "/veranstaltungen"
weight = 3

[[menu.main]]
name = "Instrumentalausbildung"
url = "/instrumentalausbildung"
weight = 15

[[menu.main]]
name = "Kontakt"
url = "/kontakt"
weight = 7


[[menu.main]]
name = "Impressum"
url = "/imprint"
weight = 11

[[menu.main]]
name = "Datenschutz"
url = "/dsgvo"
weight = 11

# [[menu.main]]
# name = "Mitglied werden"
# url = "/mitglied"
# weight = 13 

############################# Default Parameters ##########################
[params]
logo = "images/wappen.png"
author = "Paul Gerhart"
title = "Musikverein Keilberg e.V."
description = "Der Musikverein Keilberg ist eine engagierte Gemeinschaft von Musikerinnen und Musikern, die sich der Förderung und Erhaltung der Blasmusik widmet. Wir organisieren regelmäßig Konzerte, Veranstaltungen und bieten eine hochwertige musikalische Ausbildung für alle Altersgruppen. Wir proben jeden Dienstag von 20:00-22:00 Uhr in unserem Vereinsheim an der Hauptstraße 32-34, 63856 Bessenbach."
ustid = ""

################################ German Language ########################
[languages.de]
languageName = "De"
languageCode = "de-de"
weight = 2
copyright = "Copyright &copy; 2025 Musikverein Keilberg e.V."
